/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Type__4 = IDL.Record({
  'resolved' : IDL.Nat,
  'totalIssues' : IDL.Nat,
  'openIssues' : IDL.Nat,
  'inProgress' : IDL.Nat,
});
export const Type__3 = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'weight' : IDL.Nat,
});
export const Type__2 = IDL.Record({
  'id' : IDL.Nat,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'upvotes' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'reporterId' : IDL.Principal,
  'category' : IDL.Text,
  'resolvedAt' : IDL.Opt(IDL.Int),
});
export const Type__1 = IDL.Variant({ 'User' : IDL.Null, 'Admin' : IDL.Null });
export const Type = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : Type__1,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createIssue' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteIssue' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAdminStats' : IDL.Func([], [Type__4], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHeatmapData' : IDL.Func([], [IDL.Vec(Type__3)], ['query']),
  'getIssueCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getIssues' : IDL.Func([], [IDL.Vec(Type__2)], ['query']),
  'getIssuesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Type__2)], ['query']),
  'getIssuesByReporter' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Type__2)],
      ['query'],
    ),
  'getIssuesByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Type__2)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Type)], ['query']),
  'getOrCreateProfile' : IDL.Func([IDL.Text], [Type], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateIssueStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'upvoteIssue' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Type__4 = IDL.Record({
    'resolved' : IDL.Nat,
    'totalIssues' : IDL.Nat,
    'openIssues' : IDL.Nat,
    'inProgress' : IDL.Nat,
  });
  const Type__3 = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'weight' : IDL.Nat,
  });
  const Type__2 = IDL.Record({
    'id' : IDL.Nat,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'upvotes' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'reporterId' : IDL.Principal,
    'category' : IDL.Text,
    'resolvedAt' : IDL.Opt(IDL.Int),
  });
  const Type__1 = IDL.Variant({ 'User' : IDL.Null, 'Admin' : IDL.Null });
  const Type = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : Type__1,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createIssue' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteIssue' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAdminStats' : IDL.Func([], [Type__4], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHeatmapData' : IDL.Func([], [IDL.Vec(Type__3)], ['query']),
    'getIssueCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getIssues' : IDL.Func([], [IDL.Vec(Type__2)], ['query']),
    'getIssuesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Type__2)], ['query']),
    'getIssuesByReporter' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Type__2)],
        ['query'],
      ),
    'getIssuesByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Type__2)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Type)], ['query']),
    'getOrCreateProfile' : IDL.Func([IDL.Text], [Type], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateIssueStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'upvoteIssue' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };