/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Type {
  'principal' : Principal,
  'name' : string,
  'role' : Type__1,
}
export type Type__1 = { 'User' : null } |
  { 'Admin' : null };
export interface Type__2 {
  'id' : bigint,
  'lat' : number,
  'lng' : number,
  'upvotes' : bigint,
  'status' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'photoUrl' : [] | [string],
  'reporterId' : Principal,
  'category' : string,
  'resolvedAt' : [] | [bigint],
}
export interface Type__3 { 'lat' : number, 'lng' : number, 'weight' : bigint }
export interface Type__4 {
  'resolved' : bigint,
  'totalIssues' : bigint,
  'openIssues' : bigint,
  'inProgress' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createIssue' : ActorMethod<
    [string, string, string, [] | [string], number, number],
    bigint
  >,
  'deleteIssue' : ActorMethod<[bigint], boolean>,
  'getAdminStats' : ActorMethod<[], Type__4>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHeatmapData' : ActorMethod<[], Array<Type__3>>,
  'getIssueCount' : ActorMethod<[], bigint>,
  'getIssues' : ActorMethod<[], Array<Type__2>>,
  'getIssuesByCategory' : ActorMethod<[string], Array<Type__2>>,
  'getIssuesByReporter' : ActorMethod<[Principal], Array<Type__2>>,
  'getIssuesByStatus' : ActorMethod<[string], Array<Type__2>>,
  'getMyProfile' : ActorMethod<[], [] | [Type]>,
  'getOrCreateProfile' : ActorMethod<[string], Type>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateIssueStatus' : ActorMethod<[bigint, string], boolean>,
  'upvoteIssue' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];